ALTER TABLE users
ADD COLUMN age INTEGER;

ALTER TABLE users
ADD COLUMN workout_days INTEGER;

ALTER TABLE users
ADD COLUMN reminders_enabled INTEGER NOT NULL DEFAULT 1;

ALTER TABLE users
ADD COLUMN onboarding_completed INTEGER NOT NULL DEFAULT 0;